# Copyright (c) 2025 Jonathan Fontanez
# SPDX-License-Identifier: BUSL-1.1

[package]
name = "camera-python-display"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
publish = false

[dependencies]
streamlib = { path = "../../libs/streamlib" }
streamlib-python = { path = "../../libs/streamlib-python" }
tracing = { workspace = true }
tracing-log = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_json = { workspace = true }
