[package]
name = "streamlib-py"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "streamlib"
crate-type = ["cdylib"]

[dependencies]
streamlib-core = { path = "../streamlib-core" }
pyo3.workspace = true
