[package]
name = "streamlib-vulkan"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
streamlib-core = { path = "../streamlib-core" }
thiserror.workspace = true
anyhow.workspace = true
ash.workspace = true
