[package]
name = "tokio-integration"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
streamlib = { path = "../../libs/streamlib" }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
