[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "streamlib_metal"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]
dynamic = ["version"]
dependencies = [
    "wgpu>=0.24.0",
]

[tool.maturin]
module-name = "streamlib_metal"
features = ["pyo3/extension-module"]
