[package]
name = "whep-player"
version = "0.1.0"
edition = "2021"

[dependencies]
streamlib = { path = "../../libs/streamlib" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
ctrlc = "3.4"
