# Copyright (c) 2025 Jonathan Fontanez
# SPDX-License-Identifier: BUSL-1.1

[package]
name = "xpc-test"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
streamlib = { path = "../../libs/streamlib" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.'cfg(target_os = "macos")'.dependencies]
xpc-bindgen = "26.0.1"
mach2 = "0.4"
nix = { version = "0.29", features = ["socket", "uio"] }
libc = "0.2"
launchd = "0.3.0"
launchctl = "0.3.2"
